project:
  type: book
  output-dir: docs
book:
  title: "CASA0007: \n Quantitative Methods"
  author: "[Dr Huanfa Chen](https://huanfachen.github.io)"
  date: "07/03/2025"
  chapters:
    - index.qmd
    - part: "A. SQL"
      chapters:
        - W01_EDA1.qmd
        - W02_SQL.qmd
        - W03_postgis1.qmd
        - W04_postgis2.qmd
        - W05_quiz.qmd
    - part: "B. Google Earth Engine"
      chapters:
        - W06_RS.qmd
        - W07_refineries.qmd
        - W08_ISM.qmd
        - W09_blast.qmd
        - W10_ships.qmd
    - part: "GEE Textbook"
      chapters:
        - F1.qmd
        - F2.qmd
        - F4.qmd
        - F5.qmd
  repo-url: https://github.com/huanfachen/CASA0007/
  google-analytics: G-NJWVSV2MSC
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  favicon: favicon.ico
  sidebar:
    logo: logo_white.png
    collapse-level: 2

bibliography: references.bib

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    code-copy: true
    code-overflow: wrap
    highlight-style: monokai.theme
    linkcolor: "#34a832"        

  pdf:
    documentclass: scrreprt
    header-includes:
      - \makeatletter
      - \@addtoreset{chapter}{part}
      - \makeatother         
  epub:
    cover-image: cover.png
