project:
  type: book
  output-dir: docs
book:
  title: "CASA0007: \n Quantitative Methods"
  author: "[Dr Huanfa Chen](https://huanfachen.github.io), [Dr Huanfa Chen](https://huanfachen.github.io)"
  date: "08/18/2025"
  chapters:
    - index.qmd
    - part: "A. Basics"
      chapters:
        - W01_EDA1.qmd
        - W02_EDA2.qmd
        - W03_HypoTesting.qmd
        - W04_LA.qmd

    - part: "B. Correlation and Regression"
      chapters:
        - W05_Correlation.qmd
        - W06_Regression.qmd
        - W07_GLM.qmd
        - W08_MLReg.qmd
    - part: "C. Dimension Reduction & Clustering"
      chapters:
        - W09_DR.qmd
        - W10_Clustering.qmd
  repo-url: https://github.com/huanfachen/CASA0007/
  google-analytics: G-NJWVSV2MSC
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  favicon: favicon.ico
  sidebar:
    logo: logo_white.png
    collapse-level: 2

bibliography: references.bib

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    code-copy: true
    code-overflow: wrap
    highlight-style: monokai.theme
    linkcolor: "#34a832"        

  pdf:
    documentclass: scrreprt
    header-includes:
      - \makeatletter
      - \@addtoreset{chapter}{part}
      - \makeatother         
  epub:
    cover-image: cover.png
